WIP: Skip is_dirty check from matlab tools
sot/ska_helpers pull request #48
Opened 2023-08-13 13:19 UTC by jeanconn

## Description
Skip is_dirty check from matlab tools.  The gitpython is_dirty appears to use a lock that touches files in the index.  This conflicts with SVN management of the chandra_models repo (and marks the repo as modified for matlab users).  That behavior is undesireable.  This PR skips the is_dirty check if THERMAL_MODELS_FOR_MATLAB_TOOLS_SW is set.

Fixes #44 

## Interface impacts

## Testing

### Unit tests

- [x] Mac

Independent check of unit tests by [REVIEWER NAME]
- [ ] [PLATFORM]:

### Functional tests

Made a new unit test for functional testing.

2023-08-13 17:12 UTC, taldcroft commented
This seems generally fine. @jeanconn - do you understand the root cause of the index being touched? I ask because I am unable to reproduce the problem in my Windows VM in ska3. But I do note that my `git` in that env seems to be not corrupted in the sense that `git status` from the command line works fine, whereas with a corrupted install that command returns no output for me.

This is more-or-less repeating your earlier point that this might be an opportunity to fix some underlying problems in the MATLAB Ska core installation.

2023-08-13 17:30 UTC, jeanconn commented
I thought the root cause of the index being touched is that gitpython is configured such that it is doing the same thing as "git status" and using optional locks and thus does modify the index when is_dirty is used.  I found git status did the same thing in https://github.com/sot/ska_helpers/issues/44#issuecomment-1640936909 unless --no-optional-locks was configured but I was strictly looking at the svn status not a shasum.  As such, I didn't think this was caused by broken git -- I thought this was expected behavior.  I'll try to find a non-svn way to show the behavior in windows.

2023-08-13 17:51 UTC, jeanconn commented
This is just with my windows miniconda git

```
user@DESKTOP-E8FD0KK MINGW64 ~/Documents/MATLAB/FOT_Tools/Thermal_Models/chandra_models-3.49 ((3.49))
$ git --version
git version 2.34.1.windows.1

change to thermal models repo

user@DESKTOP-E8FD0KK MINGW64 ~/Documents/MATLAB/FOT_Tools/Thermal_Models/chandra_models-3.49 ((3.49))
$ which git
/c/Users/unksm/miniconda3/Library/bin/git

user@DESKTOP-E8FD0KK MINGW64 ~/Documents/MATLAB/FOT_Tools/Thermal_Models/chandra_models-3.49 ((3.49))
$ shasum .git/index
862f863f233440d6a644745c0cc20fe41b8f9f57 *.git/index

user@DESKTOP-E8FD0KK MINGW64 ~/Documents/MATLAB/FOT_Tools/Thermal_Models/chandra_models-3.49 ((3.49))
$ git status
Not currently on any branch.
nothing to commit, working tree clean

user@DESKTOP-E8FD0KK MINGW64 ~/Documents/MATLAB/FOT_Tools/Thermal_Models/chandra_models-3.49 ((3.49))
$ shasum .git/index
5b731090061f26f1fc3e71b79dbd57a5dda8820d *.git/index

user@DESKTOP-E8FD0KK MINGW64 ~/Documents/MATLAB/FOT_Tools/Thermal_Models/chandra_models-3.49 ((3.49))
$ git status
Not currently on any branch.
nothing to commit, working tree clean

user@DESKTOP-E8FD0KK MINGW64 ~/Documents/MATLAB/FOT_Tools/Thermal_Models/chandra_models-3.49 ((3.49))
$ shasum .git/index
5b731090061f26f1fc3e71b79dbd57a5dda8820d *.git/index
```
It looks like it is "stable" at that shasum after getting status in this directory, so I suppose for an *overall* underlying reason for an issue that probably speaks to @jskrist's thought that maybe doing something else before checking in the SVN would make sense "If it is, perhaps @matthewdahmer could make sure the aca model is always run before he commits the thermal models to the SVN repository to resolve this issue.".  I don't know what state information the index file stores or what state the chandra_models-3.49 repo is in and it is a binary file so it isn't really trivial to ask the file.  If I just fetch a clean chandra_models repo from git and run "git status" on that, there are no changes to the index.  I just attached the index of chandra_models-3.49 zipped in this comment.

[index.zip](https://github.com/sot/ska_helpers/files/12330064/index.zip)

2023-08-13 17:54 UTC, jeanconn commented
So I think we want to fix git in the matlab installation such that "git clone" works, but I don't think that fix would fix this.

2023-08-13 18:19 UTC, jskrist commented
I'm wondering now if the index file stores a hash of the location of the repo in it. That path would point to the creators path, then get updated when a status is run on the repo?  That would explain the behavior I've seen so far.

2023-08-13 18:43 UTC, jeanconn commented
I don't see a full path in there just looking for strings in the index (before or after git status).

2023-08-13 19:06 UTC, jeanconn commented
From various googlings, looking at https://learn.microsoft.com/en-us/archive/msdn-magazine/2017/august/devops-git-internals-architecture-and-index-files and the text "Next are five 4-byte values (device, inode, mode, user id and group id) of file-attribute metadata related to the host OS." it would not surprise me if git wrote back some data related to user and host into the file with git status and then maybe just doesn't report it in a useful fashion with "git ls-files -s" which is what I'm looking at for git's display of the index.

2023-08-14 09:54 UTC, taldcroft commented
> I'm wondering now if the index file stores a hash of the location of the repo in it. 

Bingo, this looks quite promising since I'm able to reproduce it on Mac and Windows.
```
$ cd ~/git
$ cp -rp chandra_models chandra_models-copy
$ cd chandra_models-copy
$ ls -l .git/index
$ md5 .git/index
-rw-r--r--  1 aldcroft  staff  6508 Jul 11 10:06 .git/index
MD5 (.git/index) = b3e5f7335cbb528cd0bae3bb863f4e78

$ git status

# same ls and md5 commands now
-rw-r--r--  1 aldcroft  staff  6508 Aug 14 05:47 .git/index
MD5 (.git/index) = 282cea338c0b41f8178cc82292f2dfae
```
And as @jeanconn noted this appears to be stable after the first update.

> @jskrist's thought that maybe doing something else before checking in the SVN would make sense 

YES! It looks like a simple `git status` before the SVN checkin should be sufficient?

2023-08-14 10:09 UTC, taldcroft commented
And I've been going back and forth about whether we should still merge this PR even when the process issue gets fixed.

On the one hand @jeanconn noted that the SVN checksum should provide visibility into any issue in the chandra_models repo. On the other hand, if the repo really is dirty, then running any flight tools using the dirty repo is extremely bad (hence the original idea of always raising an exception).

Thoughts?

2023-08-14 15:42 UTC, jeanconn commented
In our meeting today @taldcroft had the good question -- "but does the PR code work to get the _version_ without updating the index".  I hadn't checked the returned version so just went back in to do that and it looks OK.
```
>> pyexec('model, info = ska_helpers.chandra_models.get_data("chandra_models/xija/aca/aca_spec.json")')
>> pyexec('print(info)')
PYPROC: {'call_args': {'file_path': 'chandra_models/xija/aca/aca_spec.json', 'version': None, 'repo_path': 'None', 'require_latest_version': False, 'timeout': 5, 'read_func': 'None', 'read_func_kwargs': None}, 'version': '3.49', 'commit': '1efcc5806e914d14155ebfe69ccd61df123a5701', 'data_file_path': 'C:\\Users\\unksm\\Documents\\MATLAB\\FOT_Tools\\Thermal_Models\\chandra_models-3.49\\chandra_models\\xija\\aca\\aca_spec.json', 'repo_path': 'C:\\Users\\unksm\\Documents\\MATLAB\\FOT_Tools\\Thermal_Models\\chandra_models-3.49', 'md5': '0f300771293ac64b232f7ed82c73a6e0', 'CHANDRA_MODELS_REPO_DIR': None, 'CHANDRA_MODELS_DEFAULT_VERSION': None, 'THERMAL_MODELS_DIR_FOR_MATLAB_TOOLS_SW': 'C:\\Users\\unksm\\Documents\\MATLAB\\FOT_Tools\\Thermal_Models\\chandra_models-3.49'}
>> 
```

2023-08-14 17:07 UTC, taldcroft requested changes
OK, this looks good now. The only thing missing is documentation in the doc string of how the `get_data` function changes behavior slightly if `THERMAL_MODELS_DIR_FOR_MATLAB_TOOLS_SW` is defined.

2023-08-14 19:48 UTC, jeanconn commented
I was thinking this for docs in get_data.  Does this read OK to you @taldcroft ?
```
    ``THERMAL_MODESL_DIR_FOR_MATLAB_TOOLS_SW`` is used to define the chandra_models repository
    location when running in the MATLAB tools software environment.  If this environment
    variable is set, then the git is_dirty() check of the chandra_models directory is skipped
    as the chandra_models repository is verified via SVN in the MATLAB tools software environment.
    Users in the FOT Matlab tools should exercise caution if using locally-modified files
    for testing, as the version information reported by this function in that case will not
    be correct.
```

2023-08-14 19:51 UTC, taldcroft approved these changes
With a lien on adding the doc update in the comment.

2023-08-14 19:52 UTC, taldcroft commented
Looks good @jeanconn

2023-08-14 19:58 UTC, merged